# Generated by Django 6.0.2 on 2026-03-03 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EODOptionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='ES', max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('underlying_settlement', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('product', 'date')},
            },
        ),
        migrations.CreateModel(
            name='OptionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_symbol', models.CharField(max_length=32, unique=True)),
                ('underlying', models.CharField(max_length=20)),
                ('expiration', models.DateTimeField(db_index=True)),
                ('strike', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('option_type', models.CharField(choices=[('C', 'Call'), ('P', 'Put')], max_length=1)),
                ('settlement', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('volume', models.BigIntegerField(default=0, null=True)),
                ('open_interest', models.BigIntegerField(default=0, null=True)),
                ('dte', models.IntegerField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='options.eodoptionsnapshot')),
            ],
            options={
                'ordering': ['strike'],
                'unique_together': {('snapshot', 'raw_symbol')},
            },
        ),
    ]
