# Generated by Django 6.0.2 on 2026-03-15 06:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionChainSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='ES', max_length=10)),
                ('date', models.DateField()),
                ('label', models.CharField(max_length=50)),
                ('underlying_price', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'label'], name='options_opt_date_6b732f_idx')],
                'unique_together': {('date', 'label', 'product')},
            },
        ),
        migrations.CreateModel(
            name='OptionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.BigIntegerField(default=0)),
                ('raw_symbol', models.CharField(max_length=50)),
                ('expiration', models.DateTimeField()),
                ('strike', models.FloatField()),
                ('option_type', models.CharField(choices=[('C', 'Call'), ('P', 'Put')], max_length=1)),
                ('settlement', models.FloatField(default=0.0)),
                ('open_interest', models.IntegerField(default=0)),
                ('delta', models.FloatField(default=0.0)),
                ('dte', models.IntegerField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='options.optionchainsnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot', 'option_type', 'strike'], name='options_opt_snapsho_20623d_idx'), models.Index(fields=['instrument_id'], name='options_opt_instrum_7a751e_idx'), models.Index(fields=['dte'], name='options_opt_dte_485691_idx')],
                'unique_together': {('snapshot', 'raw_symbol')},
            },
        ),
        migrations.CreateModel(
            name='TradeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_type', models.CharField(max_length=100)),
                ('dte', models.IntegerField()),
                ('strikes', models.CharField(max_length=100)),
                ('credit_debit', models.FloatField()),
                ('max_profit', models.FloatField()),
                ('max_loss', models.FloatField()),
                ('probability', models.CharField(max_length=10)),
                ('edge', models.CharField(max_length=20)),
                ('rr_ratio', models.CharField(default='N/A', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='options.optionchainsnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot', 'strategy_type'], name='options_tra_snapsho_ce7d7f_idx')],
            },
        ),
    ]
