# Generated by Django 6.0.2 on 2026-03-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesuggestion',
            name='is_monthly',
            field=models.BooleanField(default=False),
        ),
    ]
