# Generated by Django 6.0.2 on 2026-03-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optioncontract',
            options={'ordering': ['expiration', 'strike']},
        ),
        migrations.AddField(
            model_name='optioncontract',
            name='delta',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='optioncontract',
            name='implied_vol',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='raw_symbol',
            field=models.CharField(max_length=32),
        ),
    ]
