# Generated by Django 6.0.2 on 2026-03-15 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_tradesuggestion_is_monthly'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootprintNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike', models.FloatField()),
                ('call_oi', models.IntegerField(default=0)),
                ('put_oi', models.IntegerField(default=0)),
                ('total_oi', models.IntegerField(default=0)),
                ('oi_pct', models.FloatField(default=0.0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footprint', to='options.optionchainsnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot', 'strike'], name='options_foo_snapsho_0c134a_idx')],
            },
        ),
    ]
