# Generated by Django 6.0.2 on 2026-03-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_alter_optioncontract_options_optioncontract_delta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optioncontract',
            name='gamma',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='optioncontract',
            name='theta',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='open_interest',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='volume',
            field=models.BigIntegerField(default=0),
        ),
    ]
