# Generated by Django 6.0.2 on 2026-03-15 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_footprintnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootprintBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_type', models.CharField(choices=[('WEEKLY', '01_WEEKLY'), ('MONTHLY', '02_MONTHLY'), ('QUARTERLY', '03_QUARTERLY')], max_length=20)),
                ('zone', models.CharField(max_length=50)),
                ('notional_delta', models.FloatField(default=0.0)),
                ('growth', models.FloatField(default=0.0)),
                ('volume_filter_met', models.BooleanField(default=False)),
                ('ref_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref_bins', to='options.optionchainsnapshot')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='options.optionchainsnapshot')),
            ],
            options={
                'ordering': ['bin_type', 'zone'],
            },
        ),
    ]
