# Generated by Django 6.0.2 on 2026-03-06 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_optioncontract_gamma_optioncontract_theta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_type', models.CharField(max_length=50)),
                ('dte', models.IntegerField()),
                ('strikes', models.CharField(max_length=100)),
                ('credit_debit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('breakeven_low', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('breakeven_high', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('probability', models.CharField(max_length=10)),
                ('edge', models.CharField(max_length=10)),
                ('rr_ratio', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.eodoptionsnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
