# Generated by Django 6.0.2 on 2026-03-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_footprintbin'),
    ]

    operations = [
        migrations.AddField(
            model_name='footprintbin',
            name='top_walls',
            field=models.JSONField(default=list),
        ),
    ]
