# Generated by Django 6.0.2 on 2026-03-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_tradesuggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradesuggestion',
            name='snapshot',
        ),
        migrations.AlterModelOptions(
            name='eodoptionsnapshot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='optioncontract',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='optioncontract',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='eodoptionsnapshot',
            name='product',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='eodoptionsnapshot',
            name='underlying_settlement',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='delta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='dte',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='open_interest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='raw_symbol',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='settlement',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='theta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='optioncontract',
            index=models.Index(fields=['snapshot', 'expiration', 'option_type'], name='options_opt_snapsho_89de85_idx'),
        ),
        migrations.DeleteModel(
            name='TradeSuggestion',
        ),
        migrations.RemoveField(
            model_name='optioncontract',
            name='gamma',
        ),
        migrations.RemoveField(
            model_name='optioncontract',
            name='implied_vol',
        ),
        migrations.RemoveField(
            model_name='optioncontract',
            name='underlying',
        ),
        migrations.RemoveField(
            model_name='optioncontract',
            name='volume',
        ),
    ]
