# Generated by Django 6.0.2 on 2026-03-08 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0005_remove_tradesuggestion_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eodoptionsnapshot',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='optioncontract',
            name='implied_vol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eodoptionsnapshot',
            name='product',
            field=models.CharField(db_index=True, default='ES', max_length=10),
        ),
        migrations.AlterField(
            model_name='eodoptionsnapshot',
            name='underlying_settlement',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='open_interest',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='settlement',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='optioncontract',
            unique_together={('snapshot', 'raw_symbol')},
        ),
        migrations.CreateModel(
            name='TradeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_type', models.CharField(max_length=50)),
                ('dte', models.IntegerField()),
                ('strikes', models.CharField(max_length=100)),
                ('credit_debit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('probability', models.CharField(max_length=10)),
                ('edge', models.CharField(max_length=10)),
                ('rr_ratio', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.eodoptionsnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
