# Generated by Django 6.0.2 on 2026-03-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0005_footprintbin_top_walls'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesuggestion',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
