# Generated by Django 6.0.2 on 2026-03-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0006_tradesuggestion_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionchainsnapshot',
            name='state_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
