# Generated by Django 6.0.2 on 2026-03-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0006_alter_eodoptionsnapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eodoptionsnapshot',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='eodoptionsnapshot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eodoptionsnapshot',
            name='label',
            field=models.CharField(db_index=True, default='EOD', max_length=50),
        ),
    ]
