# Generated by Django 6.0.2 on 2026-03-17 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0007_optionchainsnapshot_state_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footprintbin',
            name='ref_snapshot',
        ),
        migrations.RemoveField(
            model_name='footprintbin',
            name='snapshot',
        ),
        migrations.RemoveIndex(
            model_name='footprintnode',
            name='options_foo_snapsho_0c134a_idx',
        ),
        migrations.RemoveIndex(
            model_name='optionchainsnapshot',
            name='options_opt_date_6b732f_idx',
        ),
        migrations.RemoveIndex(
            model_name='optioncontract',
            name='options_opt_snapsho_20623d_idx',
        ),
        migrations.RemoveIndex(
            model_name='optioncontract',
            name='options_opt_instrum_7a751e_idx',
        ),
        migrations.RemoveIndex(
            model_name='optioncontract',
            name='options_opt_dte_485691_idx',
        ),
        migrations.RemoveIndex(
            model_name='tradesuggestion',
            name='options_tra_snapsho_ce7d7f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='optionchainsnapshot',
            unique_together={('date', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='optioncontract',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='optioncontract',
            name='implied_vol',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='optioncontract',
            name='theta',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='optionchainsnapshot',
            name='product',
            field=models.CharField(default='ES', max_length=20),
        ),
        migrations.AlterField(
            model_name='optionchainsnapshot',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='optionchainsnapshot',
            name='underlying_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='delta',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='instrument_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='option_type',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='raw_symbol',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='settlement',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='strike',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tradesuggestion',
            name='edge',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tradesuggestion',
            name='probability',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tradesuggestion',
            name='rr_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tradesuggestion',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.optionchainsnapshot'),
        ),
        migrations.AlterField(
            model_name='tradesuggestion',
            name='strikes',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tradesuggestion',
            name='width',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='FootprintBin',
        ),
        migrations.RemoveField(
            model_name='tradesuggestion',
            name='timestamp',
        ),
        migrations.DeleteModel(
            name='FootprintNode',
        ),
    ]
