# Generated by Django 6.0.2 on 2026-03-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0007_alter_eodoptionsnapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eodoptionsnapshot',
            options={'ordering': ['-date', '-timestamp']},
        ),
        migrations.AddField(
            model_name='eodoptionsnapshot',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
