# Generated by Django 6.0.2 on 2026-03-17 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0008_remove_footprintbin_ref_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionchainsnapshot',
            options={'ordering': ['-date', '-timestamp']},
        ),
        migrations.AlterField(
            model_name='tradesuggestion',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='options.optionchainsnapshot'),
        ),
        migrations.CreateModel(
            name='FootprintBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('call_gamma_exposure', models.FloatField(default=0.0)),
                ('put_gamma_exposure', models.FloatField(default=0.0)),
                ('net_gamma_exposure', models.FloatField(default=0.0)),
                ('oi_density', models.IntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footprints', to='options.optionchainsnapshot')),
            ],
            options={
                'ordering': ['strike_price'],
            },
        ),
    ]
