# Generated by Django 6.0.2 on 2026-03-17 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0009_alter_optionchainsnapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footprintbin',
            options={},
        ),
        migrations.RemoveField(
            model_name='footprintbin',
            name='call_gamma_exposure',
        ),
        migrations.RemoveField(
            model_name='footprintbin',
            name='put_gamma_exposure',
        ),
        migrations.RemoveField(
            model_name='optioncontract',
            name='theta',
        ),
        migrations.RemoveField(
            model_name='tradesuggestion',
            name='edge',
        ),
        migrations.AddField(
            model_name='footprintbin',
            name='is_monthly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='settlement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='strike',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='TradeOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=100)),
                ('structure', models.CharField(max_length=255)),
                ('credit_collected', models.FloatField()),
                ('max_risk', models.FloatField()),
                ('rr_ratio', models.FloatField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='options.optionchainsnapshot')),
            ],
        ),
    ]
