# Generated by Django 6.0.2 on 2026-03-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0010_alter_footprintbin_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footprintbin',
            options={'ordering': ['strike_price']},
        ),
        migrations.RemoveField(
            model_name='footprintbin',
            name='is_monthly',
        ),
        migrations.AddField(
            model_name='optioncontract',
            name='theta',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tradeoutcome',
            name='bias',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradesuggestion',
            name='edge',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
