# Generated by Django 6.0.2 on 2026-03-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0011_alter_footprintbin_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntradayOptionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('underlying_price', models.FloatField()),
                ('instrument_id', models.BigIntegerField()),
                ('raw_symbol', models.CharField(max_length=100)),
                ('expiration', models.DateField()),
                ('strike', models.FloatField()),
                ('option_type', models.CharField(max_length=1)),
                ('settlement', models.FloatField()),
                ('open_interest', models.IntegerField(default=0)),
                ('implied_vol', models.FloatField(null=True)),
                ('delta', models.FloatField(null=True)),
                ('theta', models.FloatField(null=True)),
                ('dte', models.IntegerField()),
            ],
            options={
                'ordering': ['-timestamp', 'strike'],
                'indexes': [models.Index(fields=['timestamp', 'dte'], name='options_int_timesta_3ee616_idx')],
            },
        ),
    ]
